### ISSUE TITLE
ListTable error

### ISSUE THREAD

**Issue by yaronn** [chjj/blessed#160]
The following code:

    var blessed = require("blessed");
    var screen = blessed.screen();
    var accountList = blessed.ListTable({
        parent: screen,
        label: "Loaded accounts",
        keys: true,
        fg: "white",
        selectedFg: "white",
        selectedBg: "blue",
        interactive: true,
        border: {type: "line", fg: "cyan"},
        scrollable: true
    });
    accountList.setData(
        [    ["asdasd", "asdasd"], ["asdd", "asda"] ]
    );
    screen.append(accountList)
    screen.render();

gives this error:

    TypeError: Cannot read property 'forEach' of undefined
        at ScrollableBox.Table._calculateMaxes     (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/table.js:62:12)
        at ScrollableBox.ListTable.render (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/listtable.js:166:8)
        at /home/ubuntu/tmp/node_modules/blessed/lib/widgets/screen.js:687:8
        at Array.forEach (native)
        at Screen.render (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/screen.js:684:17)
        at reposition (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/element.js:976:17)
        at ScrollableBox.on._labelScroll (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/element.js:980:5)
        at ScrollableBox.EventEmitter._emit (/home/ubuntu/tmp/node_modules/blessed/lib/events.js:90:20)
        at ScrollableBox.EventEmitter.emit (/home/ubuntu/tmp/node_modules/blessed/lib/events.js:110:12)
        at ScrollableBox.scroll (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/scrollablebox.js:276:17)

if I ommit the "parent"  property than this is the error:

    TypeError: Cannot read property 'width' of null
        at ScrollableBox.Element._getWidth (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/element.js:1091:19)
        at ScrollableBox.width (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/element.js:1105:15)
        at ScrollableBox.Table._calculateMaxes (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/table.js:79:11)
        at ScrollableBox.ListTable.setRows.ListTable.setData (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/listtable.js:93:8)
       at ScrollableBox.ListTable (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/listtable.js:66:8)
        at Function.ListTable (/home/ubuntu/tmp/node_modules/blessed/lib/widgets/listtable.js:26:12)
        at Object.<anonymous> (/home/ubuntu/tmp/5.js:4:27)
       at Module._compile (module.js:460:26)
       at Object.Module._extensions..js (module.js:478:10)
       at Module.load (module.js:355:32)
blessed@0.1.15 on ubuntu 14.04

**Comment by chjj** [comment]
Ah, I see. _calculateMaxes just sort of assumes the element is attached (I inadvertantly discovered focusing an element does this too while debugging this). I've included a few failsafes now. Thanks.
