### ISSUE TITLE
Can't set label of ListTable

### ISSUE THREAD

**Issue by b263** [chjj/blessed#175]
```javascript
var blessed = require('blessed'),
	screen = blessed.screen(),
	list = blessed.ListTable({label: 'My Label'});

screen.append(list);
screen.render();
```

The above code results in the following error message. It works with every other element I tested.

```
TypeError: Cannot read property 'length' of undefined
    at Box.Element._getShrinkContent (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1605:23)
    at Box.Element._getShrink (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1634:28)
    at Box.Element._getCoords (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1697:19)
    at ScrollableBox.Element._getShrinkBox (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1500:14)
    at ScrollableBox.Element._getShrink (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1633:24)
    at ScrollableBox.Element._getCoords (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1697:19)
    at ScrollableBox.Element.render (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/element.js:1841:21)
    at ScrollableBox.ListTable.render (/private/tmp/listtable-test/node_modules/blessed/lib/widgets/listtable.js:168:21)
    at /private/tmp/listtable-test/node_modules/blessed/lib/widgets/screen.js:738:8
    at Array.forEach (native)
```

**Comment by insanity54** [comment]
I was able to reproduce. Seems like a bug to me. Removing the 'label' option works around.

**Comment by insanity54** [comment]
I was able to reproduce. Seems like a bug to me.

[_getShrinkContent](https://github.com/chjj/blessed/blob/a79e8106ea737292d4c7e21ee7dd5bf1960dee15/lib/widgets/element.js#L1605) needs _clines to be defined, but before the render() step, _clines is not. One workaround is to add the label after the render() step.

``` javascript
screen.render();
list.setLabel('My Label');
```

**Comment by sampersand** [comment]
Another work around is to replace line 1605 in widgets/element.js with:
```
if (this._clines == null) {
   var h = 1
      , w = 1;
} else {
   var h = this._clines.length
    , w = this._clines.mwidth || 1;
}
```
