### ISSUE TITLE
How do you build?

### ISSUE THREAD

**Issue by zwhitchcox** [chjj/blessed#280]
I'm trying to use this package, but I'm getting this error:

```
ERROR in ./~/react-blessed/dist/render.js
Module build failed: ReferenceError: [BABEL] /home/zane/algos/node_modules/react-blessed/dist/render.js: Using removed Babel 5 option:
 /home/zane/algos/node_modules/react-blessed/.babelrc.optional - Put the specific transforms you want in the `plugins` option
    at Logger.error (/home/zane/algos/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/zane/algos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:20)
    at OptionManager.init (/home/zane/algos/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/home/zane/algos/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/home/zane/algos/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/home/zane/algos/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/zane/algos/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/home/zane/algos/node_modules/babel-loader/lib/index.js:133:12)
 @ ./src/app.js 13:20-44

ERROR in (webpack)/~/path-browserify/index.js
Module not found: Error: Cannot resolve module 'babel' in /usr/lib/node_modules/webpack/node_modules/path-browserify
 @ (webpack)/~/path-browserify/index.js 1:0-72
```

I thought node modules were supposed to already be build when they're on npm

**Comment by jcready** [comment]
This is an issue with the react-blessed package.
