### ISSUE TITLE
TypeError: Cannot read property 'height" of null

### ISSUE THREAD

**Issue by Orelsanpls** [chjj/blessed#281]
Hello,

I've got the following error to happend:

`TypeError: Cannot read property 'height' of null
    at Log.Element._getTop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1219:17)
    at Log.atop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1242:15)
    at Box.Element._getTop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1238:17)
    at Box.atop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1242:15)
    at Box.rtop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1279:14)
    at /home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/scrollablebox.js:207:32
    at Array.reduce (native)
    at Log.ScrollableBox._scrollBottom (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/scrollablebox.js:194:30)
    at Log.ScrollableBox.setScrollPerc (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/scrollablebox.js:381:46)
    at Immediate.<anonymous> (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/log.js:41:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)TypeError: Cannot read property 'height' of null
    at Log.Element._getTop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1219:17)
    at Log.atop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1242:15)
    at Box.Element._getTop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1238:17)
    at Box.atop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1242:15)
    at Box.rtop (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/element.js:1279:14)
    at /home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/scrollablebox.js:207:32
    at Array.reduce (native)
    at Log.ScrollableBox._scrollBottom (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/scrollablebox.js:194:30)
    at Log.ScrollableBox.setScrollPerc (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/scrollablebox.js:381:46)
    at Immediate.<anonymous> (/home/neut_g/ELIOT/eliot_backend/node_modules/blessed/lib/widgets/log.js:41:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate (timers.js:596:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)`

In my software, I'm destroying every object and I restore them, this happend after a re-launch.

When I close I perform a _.destoy()_ on every object I have and apply the following code:

`
```
      // Destroy the screen
      this.screen.destroy();
```
      // Clean the program
      this.program.clear();
      this.program.disableMouse();
      this.program.showCursor();
      this.program.normalBuffer();
      this.program.destroy();
`

My launch is:

`
```
    this.screen = blessed.screen();
    this.program = blessed.program();

```
    this.program.alternateBuffer();
    this.program.enableMouse();
    this.program.hideCursor();
    this.program.clear();
`

So actually in my software I'm ignoring all errors from blessed using a regexp but it's crap, so if you could succed to correct this one I'll be thankfull :p

Thanks

**Comment by LoganDark** [comment]
You didn't append the log element to the screen.
