### ISSUE TITLE
Widget left value reading causes exception

### ISSUE THREAD

**Issue by RossComputerGuy** [chjj/blessed#365]
```
TypeError: Cannot read property 'ileft' of null
    at Box.Element._getLeft (/home/spaceboyross/termde.js/node_modules/blessed/lib/widgets/element.js:1173:26)
    at Box.aleft (/home/spaceboyross/termde.js/node_modules/blessed/lib/widgets/element.js:1181:15)
    at Box.rleft (/home/spaceboyross/termde.js/node_modules/blessed/lib/widgets/element.js:1271:14)
    at Box.left (/home/spaceboyross/termde.js/node_modules/blessed/lib/widgets/element.js:1443:14)
    at Box.TermDE.(anonymous function).on.mouse (/home/spaceboyross/termde.js/index.js:44:41)
    at Box.EventEmitter._emit (/home/spaceboyross/termde.js/node_modules/blessed/lib/events.js:94:20)
    at Box.EventEmitter.emit (/home/spaceboyross/termde.js/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/home/spaceboyross/termde.js/node_modules/blessed/lib/widgets/screen.js:508:34)
    at emitOne (events.js:115:13)
    at Program.emit (events.js:210:7)
```

**Comment by vagos** [comment]
You might have tried to read the element's "left" value before appending it to the screen.
