### ISSUE TITLE
deno support?

### ISSUE THREAD

**Issue by andykais** [chjj/blessed#425]
More of an open question than a feature request (though the goal is deno support for this lib). How feasible would it be to implement deno support? Are there quirks in this library specific to nodejs, or does it just need a simple stdout pipe?

a simple program like so:
```ts
import blessed from 'npm:blessed'

const screen = blessed.screen({})
screen.render()
```
yields the following error:
```
error: Uncaught RangeError: Maximum call stack size exceeded
    at Function.[Symbol.hasInstance] (<anonymous>)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:35:14)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
    at new Screen (file:///home/andrew/.cache/deno/npm/registry.npmjs.org/blessed/0.1.81/lib/widgets/screen.js:36:12)
```

I am curious if there is some missing deno api here or something

**Comment by zach-is-my-name** [comment]
There's nobody minding the shop since 2015

**Comment by andykais** [comment]
dang 😞

**Comment by zach-is-my-name** [comment]
I encourage you leave it open however.  People pass by sometimes sharing their experience, and even sharing forks where they've implemented features

**Comment by andykais** [comment]
feel free to re-open. I am closing as I found another lib to do what I wanted https://www.npmjs.com/package/ink

**Comment by tracker1** [comment]
> I found another lib to do what I wanted https://www.npmjs.com/package/ink

OMG, that looks awesome/amazing...

**Comment by iArisu** [comment]
For the folks out there who will read this in the future, here are two ways to **force blessed and Deno to cooperate**:
### First (dirty hack)
- Enable **node_modules** ("nodeModulesDir": "auto")
- Open your project in **VSCode**
- Do a global search with the following:
  * Search (regex, no other toggles): `(\w+)\.prototype\.__proto__\s*=\s*(\w+)\.prototype\s*;`
  * Replace with: `Object.setPrototypeOf($1.prototype, $2.prototype); $1.prototype.constructor = $1;`
  * Files to include: `node_modules\.deno\blessed@0.1.81\node_modules\blessed\lib`

Now you can create your TUI screen (tested with blessed 0.1.81).
If any issues arise, add the following:
```js
process.stdin.setRawMode = () => void 0;
var screen = blessed.screen({
      // ...
      input: process.stdin,
      output: process.stdout,
  });
```
---
### Second (cleaner)
Deno does, *in fact*, have some \_\_proto\_\_ support, as the doc states it, with the unstable flag [--unstable-unsafe-proto](https://docs.deno.com/runtime/reference/cli/unstable_flags/).

But it's clearly marked as unsupported, the dirty hack above could be usefull if they end up removing it.

<img width="742" height="224" alt="Image" src="https://github.com/user-attachments/assets/566688c2-041b-4796-9a1d-d09d5e338400" />

One thing that could be done, though, is rewriting the whole lib with modern ES6 features (but it's a ton of work for only a few folks out there).
