### ISSUE TITLE
Error: EINVAL, invalid argument on cygwin

### ISSUE THREAD

**Issue by remoe** [chjj/blessed#56]
I try to run the test:

```
$ node test/widget.js

Error: EINVAL, invalid argument
    at new Socket (net.js:156:18)
    at process.stdin (node.js:664:19)
    at new Program (blessed\lib\program.js:41:40)
    at Program (blessed\lib\program.js:28:12)
    at new Screen (blessed\lib\widget.js:256:20)
    at Function.Screen (blessed\lib\widget.js:245:12)
    at Object.<anonymous> (blessed\test\widget.js:4:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

but it runs on CMD.exe

**Comment by vmadman** [comment]
.. which is unfortunate because Cygwin is one of the few reasonable solutions to the node/windows long paths problem.
