### ISSUE TITLE
List widget not detecting parent

### ISSUE THREAD

**Issue by giodamelio** [chjj/blessed#84]
This simple example won't work unless you specify the parent in the options.  

  var blessed = require("blessed");

```
// Create a screen object.
var screen = blessed.screen();

// Create a box perfectly centered horizontally and vertically.
var serverList = blessed.list({
    align: "center",
    mouse: true,
    width: "50%",
    height: "50%",
    top: "center",
    left: "center",
    items: [
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten"
    ]
});

// Append our box to the screen.
screen.append(serverList);
serverList.select(0);

// Quit on Escape, q, or Control-C.
screen.key(["escape", "q", "C-c"], function(ch, key) {
    return process.exit(0);
});

//  Focus our element.
serverList.focus();

// Render the screen.
screen.render();
```

It crashes with

```
TypeError: Cannot read property 'height' of null
    at ScrollableBox.Element._getTop (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:2595:17)
    at ScrollableBox.Element._getBottom.parent [as top] (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:2617:15)
    at Box.Element._getTop (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:2613:17)
    at Box.Element._getBottom.parent [as top] (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:2617:15)
    at Screen._focus (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:1439:19)
    at Screen.focusPush (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:1389:8)
    at Screen.clearRegion [as focused] (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:1467:15)
    at ScrollableBox.Node.insert (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:86:25)
    at ScrollableBox.Node.append (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:95:8)
    at ScrollableBox.List.add.List.addItem.List.appendItem (/home/giodamelio/Projects/real/Vindinium-Bots/node_modules/blessed/lib/widget.js:4262:8)
```

**Comment by blazedd** [comment]
I too had this issue. I had to render the list first with an empty list and then set the items.

**Comment by chjj** [comment]
Nice catch. Will fix.

**Comment by blazedd** [comment]
@giodamelio

For now just set the widget as parent to your screen

```
// Create a screen object.
var screen = blessed.screen();

// Create a box perfectly centered horizontally and vertically.
var serverList = blessed.list({
    parent: screen,
    align: "center",
    mouse: true,
    width: "50%",
    height: "50%",
    top: "center",
    left: "center",
    items: [
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten"
    ]
});

serverList.select(0);

// Quit on Escape, q, or Control-C.
screen.key(["escape", "q", "C-c"], function(ch, key) {
    return process.exit(0);
});

//  Focus our element.
serverList.focus();

// Render the screen.
screen.render();

```
