### ISSUE TITLE
how to make a box with scrolling content?

### ISSUE THREAD

**Issue by chad3814** [chjj/blessed#85]
I tried doing this:

``` js
var info_log = blessed.box({
    content: 'info log\n',
    scrollable: true,
    alwaysScroll: true
});
```

and then when new data comes in, I want to add a line to it so I do this:

``` js
        info_log.pushLine(line);
```

but then it crashes with this error:

```
TypeError: Cannot read property 'fake' of undefined
    at ScrollableBox.Element.pushLine (/Users/chad/grokker/node_modules/blessed/lib/widget.js:3578:38)
    at LineInputStream.lineProcessor (/Users/chad/grokker/scripts/dev_start2.js:134:21)
    at LineInputStream.emit (events.js:95:17)
    at LineInputStream._events.line (/Users/chad/grokker/node_modules/line-input-stream/lib/line-input-stream.js:8:8)
    at Array.forEach (native)
    at Socket.<anonymous> (/Users/chad/grokker/node_modules/line-input-stream/lib/line-input-stream.js:36:9)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
```

`blessed/lib/widget.js:3578` is:

``` js
  return this.insertLine(this._clines.fake.length, line);
```

how do I get _clines initialized? am I doing something wrong to make a scrolling box?

**Comment by chjj** [comment]
Odd. Will investigate.

**Comment by cristiancavalli** [comment]
@chjj Any movement on this? Seems still be an issue, getting the same error for a log. If it makes any difference I've seen elements that are detached get this error, can't seem to figure out how to attach them though..

**Comment by cristiancavalli** [comment]
@chjj  @chad3814  Hey I just figured this out (maybe) - try rendering the box element before-hand, this should cause the element to become "attached" and then the logic for pushing log lines should work flawlessly.

**Comment by chad3814** [comment]
nice that you got it to work @cristiancavalli, I bailed on using blessed :/
